// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLunEEaw_e4VDBD9RPsnljc1jh2Yz4jA',
    appId: '1:865824554968:web:5e8480195e6dd2635dfcad',
    messagingSenderId: '865824554968',
    projectId: 'bmw-flutter-d08c0',
    authDomain: 'bmw-flutter-d08c0.firebaseapp.com',
    storageBucket: 'bmw-flutter-d08c0.appspot.com',
    measurementId: 'G-XEW50145VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKI3jP6zs1URpnfdF3TeMe-OkZ2I5zztY',
    appId: '1:865824554968:android:f55c9b0c570178695dfcad',
    messagingSenderId: '865824554968',
    projectId: 'bmw-flutter-d08c0',
    storageBucket: 'bmw-flutter-d08c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqrhhT9GbPnY1wK_cdVj1-2XsjsVUss1E',
    appId: '1:865824554968:ios:928ba3f8c9adb4575dfcad',
    messagingSenderId: '865824554968',
    projectId: 'bmw-flutter-d08c0',
    storageBucket: 'bmw-flutter-d08c0.appspot.com',
    iosClientId:
        '865824554968-2pe692fkig0p5g68uommsr9i2hvn5pr5.apps.googleusercontent.com',
    iosBundleId: 'lk.flutter_app.e_commerce_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqrhhT9GbPnY1wK_cdVj1-2XsjsVUss1E',
    appId: '1:865824554968:ios:928ba3f8c9adb4575dfcad',
    messagingSenderId: '865824554968',
    projectId: 'bmw-flutter-d08c0',
    storageBucket: 'bmw-flutter-d08c0.appspot.com',
    iosClientId:
        '865824554968-2pe692fkig0p5g68uommsr9i2hvn5pr5.apps.googleusercontent.com',
    iosBundleId: 'lk.flutter_app.e_commerce_app',
  );
}
